name: Build release
on:
  push:
    tags:
      - 'testv*'
jobs:
  call-test-workflow:
    uses: ./.github/workflows/test-workflow.yml
    with:
      node-version: '18'
  call-release-workflow:
    uses:  ./.github/workflows/release-workflow.yml
    with:
      node-version: '18'
