name: Build release
on:
  push:
    tags:
      - 'testv*'
jobs:
  test-workflow:
    uses: ./.github/workflows/test-workflow.yml
    with:
      node-version: ${{ vars.NODE_VERSION }}
  release-workflow:
    uses:  ./.github/workflows/release-workflow.yml
    needs: test-workflow
    with:
      node-version: ${{ vars.NODE_VERSION }}
